- name: MariaDB installation
  hosts: mariadbs
  become: yes
  tasks:
    - name: Ensure firewalld is installed
      apt:
        name: firewalld
        state: present
        update_cache: yes

    - name: Enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Permit SSH (port 22)
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Permit MariaDB port (3306)
      ansible.posix.firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Import MariaDB GPG key
      apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: present

    - name: Add MariaDB APT repository
      apt_repository:
        repo: deb [arch=amd64] http://ftp.osuosl.org/pub/mariadb/repo/10.6/ubuntu focal main
        state: present
        filename: mariadb

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Start MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Verify installation
      command: mysql --version
      register: mysql_version

    - name: Mostrar versión de MariaDB
      debug:
        var: mysql_version.stdout_lines
